# Day 10: Hoof It
```
You all arrive at a Lava Production Facility on a floating island in the sky. As the others begin to search the massive industrial complex, you feel a small nose boop your leg and look down to discover a reindeer wearing a hard hat.

The reindeer is holding a book titled "Lava Island Hiking Guide". However, when you open the book, you discover that most of it seems to have been scorched by lava! As you're about to ask how you can help, the reindeer brings you a blank topographic map of the surrounding area (your puzzle input) and looks up at you excitedly.

Perhaps you can help fill in the missing hiking trails?

The topographic map indicates the height at each position using a scale from 0 (lowest) to 9 (highest). For example:

0123
1234
8765
9876
Based on un-scorched scraps of the book, you determine that a good hiking trail is as long as possible and has an even, gradual, uphill slope. For all practical purposes, this means that a hiking trail is any path that starts at height 0, ends at height 9, and always increases by a height of exactly 1 at each step. Hiking trails never include diagonal steps - only up, down, left, or right (from the perspective of the map).

You look up from the map and notice that the reindeer has helpfully begun to construct a small pile of pencils, markers, rulers, compasses, stickers, and other equipment you might need to update the map with hiking trails.

A trailhead is any position that starts one or more hiking trails - here, these positions will always have height 0. Assembling more fragments of pages, you establish that a trailhead's score is the number of 9-height positions reachable from that trailhead via a hiking trail. In the above example, the single trailhead in the top left corner has a score of 1 because it can reach a single 9 (the one in the bottom left).

This trailhead has a score of 2:

...0...
...1...
...2...
6543456
7.....7
8.....8
9.....9
(The positions marked . are impassable tiles to simplify these examples; they do not appear on your actual topographic map.)

This trailhead has a score of 4 because every 9 is reachable via a hiking trail except the one immediately to the left of the trailhead:

..90..9
...1.98
...2..7
6543456
765.987
876....
987....
This topographic map contains two trailheads; the trailhead at the top has a score of 1, while the trailhead at the bottom has a score of 2:

10..9..
2...8..
3...7..
4567654
...8..3
...9..2
.....01
Here's a larger example:

89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
This larger example has 9 trailheads. Considering the trailheads in reading order, they have scores of 5, 6, 5, 3, 1, 3, 5, 3, and 5. Adding these scores together, the sum of the scores of all trailheads is 36.

The reindeer gleefully carries over a protractor and adds it to the pile. What is the sum of the scores of all trailheads on your topographic map?
```

In [1]:
import re
import sys
sys.path.append("..")

from common_processing import read_lines, read_as_character_array,\
    read_columns, read_diagonals

test_path = "test.txt"
data_path = "data.txt"

topo_map = read_as_character_array(test_path).astype(int)
topo_map

array([[8, 9, 0, 1, 0, 1, 2, 3],
       [7, 8, 1, 2, 1, 8, 7, 4],
       [8, 7, 4, 3, 0, 9, 6, 5],
       [9, 6, 5, 4, 9, 8, 7, 4],
       [4, 5, 6, 7, 8, 9, 0, 3],
       [3, 2, 0, 1, 9, 0, 1, 2],
       [0, 1, 3, 2, 9, 8, 0, 1],
       [1, 0, 4, 5, 6, 7, 3, 2]])

In [2]:
# Approach:
""" 
For every 0, get a list of neighbours with elevation 0 + 1 recursively, then
when the elevation is 9, return the length of the recursive list's last step, that is
the score of this 0.

Repeat for each 0
"""

" \nFor every 0, get a list of neighbours with elevation 0 + 1 recursively, then\nwhen the elevation is 9, return the length of the recursive list's last step, that is\nthe score of this 0.\n\nRepeat for each 0\n"

In [ ]:
import numpy as np
class Day10:
    def __init__(self, txt_path: str):
        self.topo_map = read_as_character_array(txt_path).astype(int)
        self.hiking_map = np.ones_like(self.topo_map) * -1

        pass
    def __str__(self):
        """ 
        Print map
        """
        return str(
            print(
                "Topographic map: \n",self.topo_map.view(),
                "\n\n Hikes Map: \n", self.hiking_map.view()
            )
        )
    
    def find_hikes(self):
        """ 
        Find all hinkes and write them into the hiking map for debugging.
        """

        pass
    
    def get_next_hinking_steps(self, position: tuple) -> list[tuple]:
        """ 
        Given a location on the map, retrieve the lists of possible next steps,
        where elevation goes up by one
        """
        start_elevation = self.get_elevation(position)
        if start_elevation == 9:
            return []
        
        neighbours = self.get_neighbours(position)
        n_elevations = [self.get_elevation(n) for n in neighbours]
    
        return [
            n for n, e in zip(neighbours, n_elevations) 
            if (e == start_elevation + 1)
        ]

    def get_elevation(self, position: tuple) -> int:
        """ get the elevation on the map"""
        try:
            return self.topo_map[*position]
        except Exception as e:
            print(e, "Position: ", position)
    
    def get_neighbours(self, position) -> list[tuple]:
        """ return valid neighbour indeces for a postion"""

        n, m = self.topo_map.shape

        # All posible indeces for neighbours:
        directions = [
            (1, 0), (-1, 0),
            (0, 1), (0, -1),
        ]
        neighbours = [
            tuple(map(lambda i, j: i + j, position, d)) 
            for d in directions
        ]

        # for k, neighbour in enumerate(neighbours):
        #     i, j = neighbour[0], neighbour[1]

        #     if i < 0 or i >= n or j < 0 or j >= m:
        #         print("pop neighbour: ", k, neighbour)

        # NOTE: This changes the lenght of the list as it iterates, so its a no-go
        #         neighbours.pop(k)

        # Update the whole list instead, with possitive logic.
        neighbours = [(i, j) for i, j in neighbours if 0 <= i < n and 0 <= j < m]

        return neighbours
    
    def update_hinking_map(self, position: tuple):
        """ Write a position on the hinking map """
        self.hiking_map[*position] = self.topo_map[*position]

day10 = Day10(test_path)
print(day10)
day10.get_next_hinking_steps((0,2))


Topographic map: 
 [[8 9 0 1 0 1 2 3]
 [7 8 1 2 1 8 7 4]
 [8 7 4 3 0 9 6 5]
 [9 6 5 4 9 8 7 4]
 [4 5 6 7 8 9 0 3]
 [3 2 0 1 9 0 1 2]
 [0 1 3 2 9 8 0 1]
 [1 0 4 5 6 7 3 2]] 

 Hikes Map: 
 [[-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]]
None


[(1, 2), (0, 3)]

In [10]:
# Get the score of a 0
day10 = Day10(test_path)
score = 0
starting_position = (0,2)
print(starting_position, day10.topo_map[*starting_position])
day10.update_hinking_map(starting_position)
print(day10.hiking_map)


(0, 2) 0
[[-1 -1  0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]]


In [11]:
day10.get_next_hinking_steps(starting_position)


[(1, 2), (0, 3)]

In [5]:
# get the next steps:
next_steps = day10.get_next_hinking_steps(starting_position)
print(next_steps)
for ns in next_steps:
    day10.update_hinking_map(ns)

print(day10.hiking_map)

[(1, 2), (0, 3)]
[[-1 -1  0  1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]]


In [6]:
# Iterate over the restult
for iteration in range(10):
    # NOTE: this overrides the dictionary with the fisrt element in the loop
    for pos in set(next_steps):
        next_steps.remove(pos)
        if day10.hiking_map[*pos] == 9:
            score +=1
            continue
        
        for step in day10.get_next_hinking_steps(pos):
            next_steps.append(step)
        day10.update_hinking_map(pos)

        # Try to see what is going on with the trail map
    # print(day10.hiking_map)
        
    set(next_steps)
print(score)

5


In [7]:
road = [starting_position]
for iteration in range(0,10):
    next_steps = day10.get_next_hinking_steps(pos)


In [8]:
# Get the score for a different "0":
day10 = Day10(test_path)
score = 0
starting_position = (0,4)
day10.update_hinking_map(starting_position)

# get the next steps:
next_steps = day10.get_next_hinking_steps(starting_position)
print(next_steps)
for ns in next_steps:
    day10.update_hinking_map(ns)

for iteration in range(10):
    # NOTE: this overrides the dictionary with the fisrt element in the loop
    for pos in set(next_steps):
        next_steps.remove(pos)
        if day10.hiking_map[*pos] == 9:
            score +=1
            continue
        print(pos)
        print(day10.topo_map[*pos])
        print(next_steps)
        for step in day10.get_next_hinking_steps(pos):
            next_steps.append(step)
        day10.update_hinking_map(pos)

        # Try to see what is going on with the trail map
    # print(day10.hiking_map)
        
    set(next_steps)
print(score)

print(day10.hiking_map)


[(1, 4), (0, 5), (0, 3)]
(0, 3)
1
[(1, 4), (0, 5)]
(1, 4)
1
[(0, 5), (1, 3)]
(0, 5)
1
[(1, 3), (1, 3)]
(1, 3)
2
[(1, 3), (0, 6)]
(0, 6)
2
[(1, 3), (2, 3)]
(2, 3)
3
[(1, 3), (0, 7)]
(0, 7)
3
[(1, 3), (3, 3), (2, 2)]


IndexError: index 8 is out of bounds for axis 1 with size 8

## Second atempt at this

simplify the question:

- I need to find all 9's that are accesible from a given 0, meaning there is **at least** 1 smooth path from 0 to 9

In [82]:
""" 
start a 0

check all 1's next to the 0
for each one, check for 2's 
... 

for each 8, check for 9
record the location of that 9

once all paths either fail to reach a 9 or reach one, count the unique
positions for 9 that are reachable from that 0
"""

" \nstart a 0\n\ncheck all 1's next to the 0\nfor each one, check for 2's \n... \n\nfor each 8, check for 9\nrecord the location of that 9\n\nonce all paths either fail to reach a 9 or reach one, count the unique\npositions for 9 that are reachable from that 0\n"

In [123]:
day10 = Day10(txt_path=test_path)
print(day10)

Topographic map: 
 [[8 9 0 1 0 1 2 3]
 [7 8 1 2 1 8 7 4]
 [8 7 4 3 0 9 6 5]
 [9 6 5 4 9 8 7 4]
 [4 5 6 7 8 9 0 3]
 [3 2 0 1 9 0 1 2]
 [0 1 3 2 9 8 0 1]
 [1 0 4 5 6 7 3 2]] 

 Hikes Map: 
 [[-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]]
None


In [124]:
# Find all starts
zero_indeces = np.where(day10.topo_map == 0)
all_zeros = [(int(x), int(y)) for x,y in zip(zero_indeces[0], zero_indeces[1])]
all_zeros

[(0, 2), (0, 4), (2, 4), (4, 6), (5, 2), (5, 5), (6, 0), (6, 6), (7, 1)]

In [125]:
# Test with first trailhead
start = all_zeros[1]
next_steps = day10.get_next_hinking_steps(start)
print(next_steps)

for nx in next_steps:
    print(day10.get_next_hinking_steps(nx))

[(1, 4), (0, 5), (0, 3)]
[(1, 3)]
[(0, 6)]
[(1, 3)]


In [128]:

start = all_zeros[0]
next_steps = day10.get_next_hinking_steps(start)
for iteration in range(8):
    iteration_next_steps = []

    for n in next_steps:
        iteration_next_steps.extend(day10.get_next_hinking_steps(n))

    # This removes duplicated positions
    next_steps = set(iteration_next_steps)
    print(next_steps)

{(1, 3)}
{(2, 3)}
{(3, 3), (2, 2)}
{(3, 2)}
{(3, 1), (4, 2)}
{(2, 1), (4, 3)}
{(4, 4), (1, 1), (2, 0)}
{(0, 1), (3, 4), (5, 4), (3, 0), (4, 5)}


In [129]:
# The lenght of the set at the last iteration is the score of the trailhead.
score = 0
score += len(next_steps)

print(score)

5


In [130]:
# Put all together:
zero_indeces = np.where(day10.topo_map == 0)
all_zeros = [(int(x), int(y)) for x,y in zip(zero_indeces[0], zero_indeces[1])]

all_scores = []
for this_zero in all_zeros:
    next_steps = day10.get_next_hinking_steps(this_zero)
    for iteration in range(8):
        iteration_next_steps = []

        for n in next_steps:
            iteration_next_steps.extend(day10.get_next_hinking_steps(n))

        # This removes duplicated positions
        next_steps = set(iteration_next_steps)

    this_zero_score = len(next_steps)
    all_scores.append(this_zero_score)

print(all_scores)
print("Total hiking score: ", sum(all_scores))

[5, 6, 5, 3, 1, 3, 5, 3, 5]
Total hiking score:  36


# Full topographic map:

In [ ]:
day10 = Day10(txt_path=data_path)

zero_indeces = np.where(day10.topo_map == 0)
all_zeros = [(int(x), int(y)) for x,y in zip(zero_indeces[0], zero_indeces[1])]

all_scores = []
for this_zero in all_zeros:
    next_steps = day10.get_next_hinking_steps(this_zero)
    for iteration in range(8):
        iteration_next_steps = []

        for n in next_steps:
            iteration_next_steps.extend(day10.get_next_hinking_steps(n))

        # This removes duplicated positions
        next_steps = set(iteration_next_steps)

    this_zero_score = len(next_steps)
    all_scores.append(this_zero_score)

print("Total hiking score: ", sum(all_scores))

Total hiking score:  629


# Part 2

```
The reindeer spends a few minutes reviewing your hiking trail map before realizing something, disappearing for a few minutes, and finally returning with yet another slightly-charred piece of paper.

The paper describes a second way to measure a trailhead called its rating. A trailhead's rating is the number of distinct hiking trails which begin at that trailhead. For example:

.....0.
..4321.
..5..2.
..6543.
..7..4.
..8765.
..9....
The above map has a single trailhead; its rating is 3 because there are exactly three distinct hiking trails which begin at that position:

.....0.   .....0.   .....0.
..4321.   .....1.   .....1.
..5....   .....2.   .....2.
..6....   ..6543.   .....3.
..7....   ..7....   .....4.
..8....   ..8....   ..8765.
..9....   ..9....   ..9....
Here is a map containing a single trailhead with rating 13:

..90..9
...1.98
...2..7
6543456
765.987
876....
987....
This map contains a single trailhead with rating 227 (because there are 121 distinct hiking trails that lead to the 9 on the right edge and 106 that lead to the 9 on the bottom edge):

012345
123456
234567
345678
4.6789
56789.
Here's the larger example from before:

89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
Considering its trailheads in reading order, they have ratings of 20, 24, 10, 4, 1, 4, 5, 8, and 5. The sum of all trailhead ratings in this larger example topographic map is 81.

You're not sure how, but the reindeer seems to have crafted some tiny flags out of toothpicks and bits of paper and is using them to mark trailheads on your topographic map. What is the sum of the ratings of all trailheads?
```

In [ ]:
## Now with ranking
""" 
This should be easy, for every possible way to reach the 9, we have a repeated element
on 'next_steps', so we remove the set() casting on each iteration
"""

In [ ]:
day10 = Day10(txt_path=test_path)

zero_indeces = np.where(day10.topo_map == 0)
all_zeros = [(int(x), int(y)) for x,y in zip(zero_indeces[0], zero_indeces[1])]

all_scores = []
for this_zero in all_zeros:
    next_steps = day10.get_next_hinking_steps(this_zero)
    for iteration in range(8):
        iteration_next_steps = []

        for n in next_steps:
            iteration_next_steps.extend(day10.get_next_hinking_steps(n))

        # We keep the whole list instead, not unique elements
        next_steps = iteration_next_steps

    this_zero_score = len(next_steps)
    all_scores.append(this_zero_score)
print(all_scores)
print("Total hiking score: ", sum(all_scores))

[20, 24, 10, 4, 1, 4, 5, 8, 5]
Total hiking score:  81


In [139]:
# Repeat with full data
day10 = Day10(txt_path=data_path)

zero_indeces = np.where(day10.topo_map == 0)
all_zeros = [(int(x), int(y)) for x,y in zip(zero_indeces[0], zero_indeces[1])]

all_scores = []
for this_zero in all_zeros:
    next_steps = day10.get_next_hinking_steps(this_zero)
    for iteration in range(8):
        iteration_next_steps = []

        for n in next_steps:
            iteration_next_steps.extend(day10.get_next_hinking_steps(n))

        # We keep the whole list instead, not unique elements
        next_steps = iteration_next_steps

    this_zero_score = len(next_steps)
    all_scores.append(this_zero_score)

print("Total hiking score: ", sum(all_scores))

Total hiking score:  1242
